/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_HYS_EN 0x20u     /*!<@brief Enable hysteresis */
#define IOCON_PIO_INV_DI 0x00u     /*!<@brief Input not invert */
#define IOCON_PIO_MODE_INACT 0x00u /*!<@brief No addition pin function */
#define IOCON_PIO_OD_DI 0x00u      /*!<@brief Disables Open-drain function */

/*! @name PIO0_0 (number 22), CN7[3]/CN8[8]/JP2/PIO0_0
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_4 (number 7), CN6[7]/CN8[7]/CN5[5]/JP24/PIO0_4
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PIO0_1 (number 15), CN7[10]/CN3[5]/CN5[6]/U4[6]/PIO0_1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segA_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segA_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segA_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segA_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segA_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_7 (number 20), CN7[5]/CN3[2]/JP23/CN5[4]/PIO0_7
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segC_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segC_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segC_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segC_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segC_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_17 (number 3), CN6[3]/CN5[3]/PIO0_17
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segD_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segD_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segD_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segD_PIN 17U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segD_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_16 (number 2), CN6[2]/CN5[2]/U4[1]/PIO0_16
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segE_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segE_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segE_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segE_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_11 (number 10), CN6[10]/CN8[3]/D4/PIO0_11/M_PIO0_11
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Dig1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Dig1_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_Dig1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_Dig1_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Dig1_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_12 (number 5), S2/CN8[6]/CN6[5]/D3/M_PIO0_12/PIO0_12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Dig2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Dig2_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_Dig2_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_Dig2_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Dig2_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_13 (number 4), S1/CN8[4]/CN6[4]/D2/M_PIO0_13/PIO0_13
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Dig3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Dig3_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_Dig3_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_Dig3_PIN 13U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Dig3_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_14 (number 23), CN7[2]/CN3[1]/JP4/PIO0_14
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Dig4_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Dig4_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_Dig4_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_Dig4_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Dig4_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_8 (number 17), CN7[8]/CN3[7]/R20/U4[5]/PIO0_8/ISP_U0_RXD_DS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segB_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segB_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segB_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segB_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segB_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_9 (number 16), CN7[9]/CN3[6]/R13/U4[2]/PIO0_9/ISP_U0_TXD_DS
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segF_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segF_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segF_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segF_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segF_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_19 (number 24), CN7[1]/CN8[2]/PIO0_19
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_segG_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_segG_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_segG_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_segG_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_segG_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
