/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: LPC804
package_id: LPC804M101JDH24
mcu_data: ksdk2_0
processor_version: 14.0.0
board: LPCXpresso804
pin_labels:
- {pin_num: '10', pin_signal: PIO0_11/ADC_6/WKTCLKIN, label: 'CN6[10]/CN8[3]/D4/PIO0_11/M_PIO0_11', identifier: LED_BLUE;Dig1}
- {pin_num: '5', pin_signal: PIO0_12, label: 'S2/CN8[6]/CN6[5]/D3/M_PIO0_12/PIO0_12', identifier: LED_GREEN;S2;Dig2}
- {pin_num: '4', pin_signal: PIO0_13/ADC_10, label: 'S1/CN8[4]/CN6[4]/D2/M_PIO0_13/PIO0_13', identifier: LED_RED;S1;Dig3}
- {pin_num: '23', pin_signal: PIO0_14/ACMP_I3/ADC_2, label: 'CN7[2]/CN3[1]/JP4/PIO0_14', identifier: I2C_SCL;Dig4}
- {pin_num: '20', pin_signal: PIO0_7/ADC_1/ACMPVREF, label: 'CN7[5]/CN3[2]/JP23/CN5[4]/PIO0_7', identifier: I2C_SDA;segC}
- {pin_num: '2', pin_signal: PIO0_16/ACMP_I4/ADC_3, label: 'CN6[2]/CN5[2]/U4[1]/PIO0_16', identifier: segE}
- {pin_num: '3', pin_signal: PIO0_17/ADC_9, label: 'CN6[3]/CN5[3]/PIO0_17', identifier: segD}
- {pin_num: '15', pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, label: 'CN7[10]/CN3[5]/CN5[6]/U4[6]/PIO0_1', identifier: segA}
- {pin_num: '16', pin_signal: PIO0_9/ADC_4, label: 'CN7[9]/CN3[6]/R13/U4[2]/PIO0_9/ISP_U0_TXD_DS', identifier: segF}
- {pin_num: '17', pin_signal: PIO0_8/ADC_5, label: 'CN7[8]/CN3[7]/R20/U4[5]/PIO0_8/ISP_U0_RXD_DS', identifier: segA;segB}
- {pin_num: '24', pin_signal: PIO0_19/DACOUT, label: 'CN7[1]/CN8[2]/PIO0_19', identifier: segG}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iocon.h"
#include "fsl_swm.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '22', peripheral: USART0, signal: RXD, pin_signal: PIO0_0/ACMP_I1}
  - {pin_num: '7', peripheral: USART0, signal: TXD, pin_signal: PIO0_4/ADC_11}
  - {pin_num: '11', peripheral: ADC0, signal: 'CH, 7', pin_signal: PIO0_10/ADC_7, mode: inactive, invert: disabled, hysteresis: enabled, opendrain: disabled}
  - {pin_num: '15', peripheral: GPIO, signal: 'PIO0, 1', pin_signal: PIO0_1/ADC_0/ACMP_I2/CLKIN, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '20', peripheral: GPIO, signal: 'PIO0, 7', pin_signal: PIO0_7/ADC_1/ACMPVREF, identifier: segC, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '3', peripheral: GPIO, signal: 'PIO0, 17', pin_signal: PIO0_17/ADC_9, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '2', peripheral: GPIO, signal: 'PIO0, 16', pin_signal: PIO0_16/ACMP_I4/ADC_3, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '10', peripheral: GPIO, signal: 'PIO0, 11', pin_signal: PIO0_11/ADC_6/WKTCLKIN, identifier: Dig1, direction: OUTPUT}
  - {pin_num: '5', peripheral: GPIO, signal: 'PIO0, 12', pin_signal: PIO0_12, identifier: Dig2, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIO, signal: 'PIO0, 13', pin_signal: PIO0_13/ADC_10, identifier: Dig3, direction: OUTPUT}
  - {pin_num: '23', peripheral: GPIO, signal: 'PIO0, 14', pin_signal: PIO0_14/ACMP_I3/ADC_2, identifier: Dig4, direction: OUTPUT}
  - {pin_num: '17', peripheral: GPIO, signal: 'PIO0, 8', pin_signal: PIO0_8/ADC_5, identifier: segB, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '16', peripheral: GPIO, signal: 'PIO0, 9', pin_signal: PIO0_9/ADC_4, direction: OUTPUT, gpio_init_state: 'true'}
  - {pin_num: '24', peripheral: GPIO, signal: 'PIO0, 19', pin_signal: PIO0_19/DACOUT, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M0P */
void BOARD_InitPins(void)
{
    /* Enables clock for IOCON.: enable */
    CLOCK_EnableClock(kCLOCK_Iocon);
    /* Enables clock for switch matrix.: enable */
    CLOCK_EnableClock(kCLOCK_Swm);
    /* Enables the clock for the GPIO0 module */
    CLOCK_EnableClock(kCLOCK_Gpio0);

    gpio_pin_config_t segA_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_1 (pin 15)  */
    GPIO_PinInit(BOARD_INITPINS_segA_GPIO, BOARD_INITPINS_segA_PORT, BOARD_INITPINS_segA_PIN, &segA_config);

    gpio_pin_config_t segC_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_7 (pin 20)  */
    GPIO_PinInit(BOARD_INITPINS_segC_GPIO, BOARD_INITPINS_segC_PORT, BOARD_INITPINS_segC_PIN, &segC_config);

    gpio_pin_config_t gpio0_pin0_8 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_8 (pin )  */
    GPIO_PinInit(GPIO, 0U, 8U, &gpio0_pin0_8);

    gpio_pin_config_t gpio0_pin0_9 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_9 (pin )  */
    GPIO_PinInit(GPIO, 0U, 9U, &gpio0_pin0_9);

    gpio_pin_config_t Dig1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_11 (pin 10)  */
    GPIO_PinInit(BOARD_INITPINS_Dig1_GPIO, BOARD_INITPINS_Dig1_PORT, BOARD_INITPINS_Dig1_PIN, &Dig1_config);

    gpio_pin_config_t Dig2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_12 (pin 5)  */
    GPIO_PinInit(BOARD_INITPINS_Dig2_GPIO, BOARD_INITPINS_Dig2_PORT, BOARD_INITPINS_Dig2_PIN, &Dig2_config);

    gpio_pin_config_t Dig3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_13 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_Dig3_GPIO, BOARD_INITPINS_Dig3_PORT, BOARD_INITPINS_Dig3_PIN, &Dig3_config);

    gpio_pin_config_t gpio0_pin0_14 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U,
    };
    /* Initialize GPIO functionality on pin PIO0_14 (pin )  */
    GPIO_PinInit(GPIO, 0U, 14U, &gpio0_pin0_14);

    gpio_pin_config_t segE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_16 (pin 2)  */
    GPIO_PinInit(BOARD_INITPINS_segE_GPIO, BOARD_INITPINS_segE_PORT, BOARD_INITPINS_segE_PIN, &segE_config);

    gpio_pin_config_t segD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_17 (pin 3)  */
    GPIO_PinInit(BOARD_INITPINS_segD_GPIO, BOARD_INITPINS_segD_PORT, BOARD_INITPINS_segD_PIN, &segD_config);

    gpio_pin_config_t gpio0_pin0_19 = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 1U,
    };
    /* Initialize GPIO functionality on pin PIO0_19 (pin )  */
    GPIO_PinInit(GPIO, 0U, 19U, &gpio0_pin0_19);

    const uint32_t IOCON_INDEX_PIO0_10_config = (/* No addition pin function */
                                                 IOCON_PIO_MODE_INACT |
                                                 /* Enable hysteresis */
                                                 IOCON_PIO_HYS_EN |
                                                 /* Input not invert */
                                                 IOCON_PIO_INV_DI |
                                                 /* Disables Open-drain function */
                                                 IOCON_PIO_OD_DI);
    /* PIO0 PIN10 (coords: 11) is configured as ADC0, CH, 7. */
    IOCON_PinMuxSet(IOCON, IOCON_INDEX_PIO0_10, IOCON_INDEX_PIO0_10_config);

    /* USART0_TXD connect to P0_4 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_TXD, kSWM_PortPin_P0_4);

    /* USART0_RXD connect to P0_0 */
    SWM_SetMovablePinSelect(SWM0, kSWM_USART0_RXD, kSWM_PortPin_P0_0);

    /* ADC_CHN7 connect to P0_10 */
    SWM_SetFixedPinSelect(SWM0, kSWM_ADC_CHN7, true);

    /* Disable clock for switch matrix. */
    CLOCK_DisableClock(kCLOCK_Swm);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
